# Base Image NodeJS
FROM node:alpine

# Working Directory (WORKDIR)
WORKDIR /usr/app

# Copy package.json
COPY ./package.json .

# Run Command
RUN npm install

# Copy code from host to container
COPY . .

# Default Command
CMD [ "npm", "start" ]




